sudo: required
dist: trusty
language: node_js
node_js:
- '8.0'
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: IWikx4TFjPGihBagOVkgqUxslyi181Wak+Z3zGLo3VUIobe/b8WGVz7w3xDaNBmr+H7nuJPOUZg4IP2OkCQYhoxRyymi5pSl4CAI+UU2m0ilMLph1jYH7VK01maIcJz6Yq1ogSgP1KuYgBd/UabOWOivVS1Xa4VUo60y91xr8bbhGI7Iva9OSa21kUYDjum87mUHsAs1UZhc9AKZwIW7gjKctfEhZTdAe/uyKDeoxFc2F3QAe1XuB6YmZpNnEIs9MNyE9CwI8uV/rtgJOoFymKDwz8p+2e8pq6HJi4KkAtlKzkdh8Kd9c2UVWA9dlhpuzQ8FoLUPJy4DD5o3iq6ImPJ34RSjPUkP6EB6TFrg8E6LFSZpjaYgkT31OPgg/Ria11LMXzfLLYLHeMEe2m5CHjPcZXAScb4HD6lDGJvyf17Atap5oqTRwWYytj3zvJlFTSksgkLAfeEhxG45UqEY4AqdOWEXwzNsekOO+1E0a6GAfll7sB8f1KBbvGMKPwTdo3jY4DMCoBP8Cur1q6Y/ErtBLHX0Lv/WYmr7Iev6g6O4vuQxEHzEAroO1jCPS/obRLkoZwS4aP4KqkMMpnlcI5o3183OAwbxApKtp4+4QktRT9sCbPxzprm++dRjfgbBSSTYGntBeFMhiumfFC6JNzIr3WCpKtjgb6eAzM2xmrI=
  - secure: gUbvdv10j7jKImUEXU+gE7VCoxrxBBl4+VIFgKWSKInuusHuQZKBpMHDZrEiSzmqDzRobru9eyX+AsFLu9v/tAS38m8WtOd7T3/T4h4/STyna6Qk7Nz9M8/wm1EJUiJODin0fKZxs1xzQh4UnsMZ8MX2AmF0ITdEtFd/CXW/orIAEbZdw6kI4L+nmyaRbz7yB6kqQdW+mprH3QJxW2YoTuQh2j6MOOsstblnIfrWnSLzVliQUYnZCKAjqb3EGdeTfSD558+UE+6ASlPPwGJ+mrswMjQ4cwllH9BjRTZjdOFNKFt9YmGLFWtyh4Jo7yTEiyOp4YNz6rFo07fP5/VPuCz91RiXwbkC38o7dfLbnHhTqYDrRNhOe2t8ReISIbfXpTiGXyMVR55uPRWoI7Ht0dYeD5XrA50v47J1AXyPo8wZryZiIm2u9NPKJF6WmaZgekHvSYAE5NCFPS+VOrDsz4AdWLkupknlQXCPvPC4NZkAmaJ0SwENS02+Ay33qrxJSluCxYM1Pl91WRhupRM7un+x3Vzj3ES+Q1z184HvPwkCt8z9UZPGXfdpRUsvH77tBHm2i9YxBjX27MOmUkDKM1pLdBvflEDJtG6CNJhmGI0X/5aNZt2LSlj/uBuwOYDz/hWxtrkQ0HlXxjcrWQm0J3nfaSlz9wL4ewypS1wZGrc=
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn
before_script:
- export CI=false
- yarn build
script:
- yarn test
after_success:
- export REPO=woa-react-app
- export TAG=latest
- export HEROKU_TAG=$REPO-heroku:$COMMIT
- docker build -f heroku.Dockerfile -t $HEROKU_TAG .
- docker tag $HEROKU_TAG registry.heroku.com/$REPO/web
- docker login --username=$HEROKU_USERNAME --password=$HEROKU_AUTHTOKEN registry.heroku.com
- docker push registry.heroku.com/$REPO/web
