sudo: required
dist: trusty
language: node_js
node_js:
  # LTS version
  - "8.0"
# notifications:
#   email:
#     on_success: change # only if status change from fail to success
#     on_failure: always # if there is a fail
#     recipients:
#       - cri@webprofessor.it
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: GqDedinxS+/MRghvjnS7Li9Tfpk7pEk9mrDXlwq8hqJqURrUeS9tj5ljrJuwkaUGU1mtSoX9BroSEI/HudlIdQoeIrHxMNIqVZC1cbVZ/o3JDSN4mJKIzdUcRrUUT5zNibdqm4xjLwrk68bPse2LMTewH9LocS9JqQoCYqA77dLGVN+lGCrJ1S/vKPo3CXcBX2oMa3GAv0FcsgWhfXNzhypsZjuU81KGsPwfpv7WRlyZC1mgw5MENUtZbwgH8Q7EFxuok6rduFX5dIEfNqvK/iKJjmAtcru+K/JdNGi+1izi21GK0gBC6twb5gXAGyhWCegTQwVp5JUzlFgb7n8QPnzHbURM7GFg3LtCZJQuyU2TEOklm2LclbDUiqsYvDPTJXRrWXzWejSxSXfdBiGSu1Tb5Q6jMm1AKWUTEI4Z0SwXa2jtGhfZdwwCZhqMHJw4gHnzWp+H0ouOkoXAGdTVIad530m1PLSO1mn05llCAEOwiagLQml3yD4AqdOc5Fk0xDaPev6zXsfRbCcLHZ42zVB12MMdmaaKvGHo8LbLFex5HamjEXoBODiPB0Px4em4gnv+z0zlaTOPvrnIV6cUoQVdTtMvAz452xLNEPkqZiGexswsyTZHnaowMnu9NkLeNBqhD1MylT7y6zyGAdPx1wti+EwjA9u9vL46tCDsg2M=
  - secure: s3oI7Fu2jNKrqfIXhnGEaTg2Ke84LGWJRBkpXPc7tR6JI2NHIpRzzNQM+eXaK2ea2PgoTTFWBg9kWBVnB3+y7H5wNjVZC9Lb81Kf5wyG0ndS8dHwv6+OA5k9jnGxpo/wwL/5dP0bXIpcl16qbDuYWLIK7cu36QTmrBxouRJr561ZCyaA4xGrf8zIB5uJ7bSyGKEutsPcEDj7zrjrDd3h9MHbk1eYCxBfQtGrj044jKWwKnZ6WDIMx+LppBY0XWBStRtBK1rK2JtgD7q1PNKKbI/l09kleIInUaW2kojlYCThuFD7m/++tuz2JgSgR/uxiLYifrJvUsRBi8C9R7Fp5Sb+RBAvPLCZYSAuxMkHO8diQIvOjI1y/37Sky+ZCexytAotxH1M35jg/uuYKRxHzJY58PS0NOUBsxVZkgx7DACVbm+I/JcSUWhBEDE+dBMd2Yts5ivWclRfDW1FdTe1UN3z2vJzRHgFgUG/PCDhVa94qvFcIvqddhSO9mLhyndNNdHZqrGUQsZGQM6xwfecf0KejTJQnxG6TtuapK2ai6HkVAjDScCVoG8wpRbmja9Z6hg5QEvBAOng97+Exllu12ygBYUMPYCzepAumML85j+30+fj4OtbMEShkhfQ3mEW6mKq9AkLOni3M3oD6bIUscSD/Tt10hsmKeZMfF1hULI=
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
before_script:
  - export CI=false
  - yarn build
script:
  - yarn test
after_success:
- export REPO=woa-react-app
- export TAG=latest
- export HEROKU_TAG=$REPO-heroku:$COMMIT
- docker build -f heroku.Dockerfile -t $HEROKU_TAG .
- docker tag $HEROKU_TAG registry.heroku.com/$REPO/web
- docker login --username=$HEROKU_USERNAME --password=$HEROKU_AUTHTOKEN registry.heroku.com
- docker push registry.heroku.com/$REPO/web
# deploy:
#   skip_cleanup: true
#   provider: script
#   script: yarn build
#   on:
#     branch: ["master"]